version: build{build}

branches:
  except:
    - feature/experiments
    - feature/tests
    - project/travis

environment:
  tano_version: 2.0
  vlcqt_version: 1.0.0

  matrix:
  # MSVC x86
  - name: win32
    platform: amd64_x86
    qt: 5.5\msvc2013
    suffix: msvc2013

  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.5\msvc2013_64
    suffix: msvc2013

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - set ORIGPATH=%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%
  - set makefiles="NMake Makefiles"
  - if %APPVEYOR_REPO_TAG%==true (set nogitinfo=ON) else (set nogitinfo=OFF)

clone_folder: c:\dev\tano

install:
  - cd c:\dev
  - md install
  - md dependencies
  - cd dependencies
  - ps: $vlcqtdl = 'https://github.com/vlc-qt/vlc-qt/releases/download/' + $env:vlcqt_version + '/VLC-Qt_' + $env:vlcqt_version + '_' + $env:name + '_' + $env:suffix + '.7z'
  - ps: Start-FileDownload $vlcqtdl -FileName vlc-qt.7z
  - 7z x vlc-qt.7z > NUL
  - set PATH=C:\dev\dependencies\bin;%PATH%

before_build:
  - cd c:\dev\tano
  - md build

build_script:
  - cd build
  - cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="c:/dev/install" -DCI=ON -DNO_GIT=%nogitinfo%
  - nmake
  - nmake install
  - nmake windows

after_build:
  - cd c:\dev\install
  - if %APPVEYOR_REPO_TAG%==true (set buildname=%APPVEYOR_REPO_TAG_NAME%) else (set buildname=%tano_version%_build%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_REPO_COMMIT:~0,7%)
  - 7z a ..\tano\Tano_%buildname%_%name%_%suffix%.7z *
  - cd c:\dev\tano

artifacts:
  - path: '*.7z'
